-- checking if data is complete and checking for duplicates
select * from e.`sales-analysis`;
select count(order_id),
count(customer_id),
count(net_revenue) from e.`sales-analysis`;
select order_id, count(*) as orders from e.`sales-analysis`
group by order_id
having count(*)>1;

-- revenue, total orders by country
select country_code, sum(net_revenue) as total_net_income from e.`sales-analysis`
group by country_code;
select country_code, count(customer_id) as customer_ids from e.`sales-analysis`
group by country_code;
select country_code, count(distinct order_id) as total_orders from e.`sales-analysis`
group by country_code
order by total_orders DESC;


-- repeat customers
select customer_id, count(*) as number_of_orders from e.`sales-analysis`
group by customer_id
having count(*)>1;
select customer_id, count(*) as orders, sum(net_revenue)as total_net_revenue from e.`sales-analysis`
group by customer_id
having count(*)>1;
select customer_id, count(distinct order_id) as order_count, sum(net_revenue)as total_net_revenue from e.`sales-analysis`
group by customer_id
having count(distinct order_id)>1;


-- total_orders by customer_segment 
select customer_segment, count(distinct order_id) as order_ids from e.`sales-analysis`
group by customer_segment
order by order_ids DESC;
-- total_net_revenue by customer_segment
select customer_segment, sum(net_revenue) as total_net_revenue from e.`sales-analysis`
group by customer_segment;

-- total_orders by aquisition channel
select acquisition_channel, count(distinct order_id) as orders from e.`sales-analysis`
group by acquisition_channel
order by order_ids DESC;

-- total revenue by customer segment and acquisition channel
select customer_segment, acquisition_channel, sum(net_revenue)as total_net_revenue from e.`sales-analysis`
group by customer_segment, acquisition_channel
order by total_net_revenue desc;

alter table e.`sales-analysis` add column year int, add column month int;
update e.`sales-analysis` set year= YEAR(date),
month= MONTH(date);
-- total net revenue by month
select * from e.`sales-analysis`;
select month, year, sum(net_revenue) as total_net_revenue from e.`sales-analysis`
group by month, year 
order by total_net_revenue desc;
-- total revenue per quarter
select YEAR(date) as year, quarter(date) as quarter, sum(net_revenue) as total_net_revenue
from e.`sales-analysis`
group by YEAR(date), quarter(date)
order by year, quarter;
-- total refund per country
select country_code, sum(refund_amount) as total_refund from e.`sales-analysis`
group by country_code
order by total_refund desc;
-- repeat customer vs acquisition channel
select customer_id, count(distinct order_id) as order_count, acquisition_channel from e.`sales-analysis`
group by customer_id, acquisition_channel
having count(distinct order_id)>1;
-- total revenue generated by each repeat customer
select customer_id, count(distinct order_id)as order_count, sum(net_revenue) as total_net_revenue 
from e.`sales-analysis`
group by customer_id
having count(distinct order_id) >1;
-- total reveneue generated by one-time customers and repeat customers
select customer_id, count(distinct order_id)as order_count, sum(net_revenue) as total_net_revenue 
from e.`sales-analysis`
group by customer_id
having count(distinct order_id) >=1;

-- total refund colllected per customers
select count(distinct refund_amount) as count_of_refund, customer_id from e.`sales-analysis`
group by customer_id
order by count_of_refund desc;

-- average revenue generated per  and the customer segment
select customer_id, customer_segment, sum(net_revenue) as total_net_revenue from e.`sales-analysis`
group by customer_segment, customer_id
order by total_net_revenue desc;
with total_net_revenue as (
select customer_id, customer_segment, sum(net_revenue) as total_net_revenue from e.`sales-analysis`
group by customer_segment, customer_id
order by total_net_revenue desc
)
select customer_id, customer_segment, avg(total_net_revenue) as average_net_revenue from total_net_revenue
group by customer_segment, customer_id
order by average_net_revenue ; 

-- orders per customer and the acquisition channel
select acquisition_channel, customer_id, count(distinct order_id)as count_of_orders from e.`sales-analysis`
group by acquisition_channel, customer_id
order by count_of_orders;
with count_of_orders as (
select acquisition_channel, customer_id, count(distinct order_id)as count_of_orders from e.`sales-analysis`
group by acquisition_channel, customer_id
order by count_of_orders
)
select acquisition_channel, sum(count_of_orders) as sum_of_orders from count_of_orders
group by acquisition_channel
order by sum_of_orders;

select customer_id, sum(net_revenue) as total_net_revenue from e.`sales-analysis`
group by customer_id
having total_net_revenue > (
select avg(total_net_revenue)
from (
select customer_id, sum(net_revenue) as total_net_revenue from e.`sales-analysis`
group by customer_id) as total_net_revenue
)
order by total_net_revenue desc;

-- total revenue per order
select order_id, sum(net_revenue) as total_net_revenue from e.`sales-analysis`
group by order_id
having sum(net_revenue) > (
select avg(total_net_revenue)
from(
select order_id, sum(net_revenue) as total_net_revenue from e.`sales-analysis`
group by order_id) as total_net_revenue
)
order by total_net_revenue desc;
-- top 10 customers with highest net_revenue
select customer_id, sum(net_revenue) as total_net_revenue from e.`sales-analysis`
group by customer_id
order by total_net_revenue desc
limit 10;

select month, year, sum(net_revenue) from e.`sales-analysis`
group by month, year;

-- country with highest repeating customers
select country_code, customer_id, count(order_id) as order_count from e.`sales-analysis`
group by country_code, customer_id;
with order_count as ( 
select country_code, customer_id, count(order_id) as order_count from e.`sales-analysis`
group by country_code, customer_id)
select country_code, sum(order_count) as order_sum from order_count
group by country_code
order by order_sum;
-- customer and customer segment rank by revenue
select customer_id, customer_segment, sum(net_revenue) as total_net_revenue, 
rank() over(
partition by customer_segment
order by sum(net_revenue) desc) as revenue_rank from e.`sales-analysis`
group by customer_id, customer_segment
order by customer_segment, revenue_rank;

-- revenue percent by country
select country_code, sum(net_revenue) as country_revenue, 
sum(net_revenue)/ (select sum(net_revenue) from e.`sales-analysis`) * 100 as revenue_percentage
from e.`sales-analysis`
group by country_code
order by revenue_percentage desc;
